# Generated by Django 2.1 on 2019-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_custommetric_customstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstat',
            name='label',
        ),
        migrations.RemoveField(
            model_name='customstat',
            name='username',
        ),
        migrations.AddField(
            model_name='custommetric',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
