# Generated by Django 2.1 on 2019-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190827_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommetric',
            name='label',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
